import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/Header";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "coffe shop",
  description: "Generated by techsa team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-dana bg-body">
        <Header/>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
