import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/Header";

export const metadata: Metadata = {
  title: "coffe shop",
  description: "Generated by techsa team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-dana">
        <Header/>
        {children}
      </body>
    </html>
  );
}
