import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import NotificationContainer from "@/Components/NotificationContainer";

export const metadata: Metadata = {
  title: "coffe shop",
  description: "Generated by techsa team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-dana bg-body">
        <Header />
        {children}
        <NotificationContainer />
        <Footer />
      </body>
    </html>
  );
}
